name: macOS Builds

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15-intel, macos-14]
        include:
          - os: macos-15-intel
            arch: x64
          - os: macos-14
            arch: arm64
      fail-fast: false
        
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Get OS version
        run: |
          echo "OS_VERSION=$(sw_vers -productVersion | cut -d . -f 1,2)" >> $GITHUB_ENV

      - if: ${{ matrix.os == 'macos-15-intel' }}
        name: Install MacPorts (x64)
        run: |          
          wget https://github.com/macports/macports-base/releases/download/v2.11.6/MacPorts-2.11.6-15-Sequoia.pkg
          sudo installer -pkg MacPorts-2.11.6-15-Sequoia.pkg -target /

      - if: ${{ matrix.os == 'macos-14' }}
        name: Install MacPorts (arm64)
        run: |          
          wget https://github.com/macports/macports-base/releases/download/v2.11.6/MacPorts-2.11.6-14-Sonoma.pkg
          sudo installer -pkg MacPorts-2.11.6-14-Sonoma.pkg -target /
          export
          PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          
      - name: Install base ports
        run: |          
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          sudo port selfupdate
          sudo port install pkgconfig
          sudo port install automake
          sudo port install autoconf
          sudo port install libtool
          sudo port install cmake
          sudo port install glib2 +quartz
          sudo port install gtkmm3 +quartz
          sudo port install libomp
          sudo port install clang-17
          sudo port install librsvg-devel
          sudo port install lensfun
          sudo port install exiv2
          sudo port install fftw-3-single +openmp
          sudo port install openexr
          sudo port install lcms2
          sudo port install adwaita-icon-theme
          sudo port install meson
          sudo port install dbus
          sudo port install simde

      - name: Install gtk-osx-application-gtk3
        run: |
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          INSTDIR=/opt/art-deps
          wget https://distfiles.macports.org/gtk-osx-application/gtk-mac-integration-3.0.2.tar.xz
          xzcat gtk-mac-integration-3.0.2.tar.xz | tar x
          cd gtk-mac-integration-3.0.2
          CC=/opt/local/bin/clang-mp-17 \
            CXX=/opt/local/bin/clang++-mp-17 \
            ./configure --prefix=$INSTDIR --with-gtk3
          make -j$(nproc)
          sudo make install

      - name: Install CTL
        run: |
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          INSTDIR=/opt/art-deps
          git clone --depth 1 https://github.com/ampas/CTL.git
          mkdir build-CTL
          cd build-CTL
          /opt/local/bin/cmake \
            -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-17 \
            -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-17 \
            -DCMAKE_INSTALL_PREFIX=$INSTDIR \
            -DCMAKE_BUILD_TYPE=Release \
            ../CTL
          make -j$(nproc)
          sudo make install

      - name: Install OpenColorIO
        run: |
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          INSTDIR=/opt/art-deps
          OCIO_VERSION='2.4.0'
          mkdir ocio
          cd ocio
          wget https://github.com/AcademySoftwareFoundation/OpenColorIO/archive/refs/tags/v${OCIO_VERSION}.tar.gz
          tar xzf v${OCIO_VERSION}.tar.gz
          mkdir build
          cd build
          /opt/local/bin/cmake \
            -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-17 \
            -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-17 \
            -DCMAKE_INSTALL_PREFIX=$INSTDIR \
            -DCMAKE_BUILD_TYPE=Release \
            -DOCIO_BUILD_PYTHON=OFF \
            -DOCIO_BUILD_APPS=0 \
            -DOCIO_BUILD_TESTS=0 \
            -DOCIO_BUILD_GPU_TESTS=0 \
            ../OpenColorIO-${OCIO_VERSION}
          make -j$(nproc)
          sudo make install

      - name: Install custom GTK+ with colorspaces support
        run: |
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          wget https://download.gnome.org/sources/gtk+/3.24/gtk%2B-3.24.43.tar.xz
          tar xzf gtk+-3.24.43.tar.xz
          cd gtk+-3.24.43
          patch -p1 < ../repo/patches/macos/gdk-window-quartz-colorspace.patch
          INSTDIR=/opt/art-deps/gtk 
          meson setup build
          meson configure build \
            --prefix $INSTDIR \
            --buildtype release \
            -Ddebug=false \
            -Ddemos=false \
            -Dexamples=false \
            -Dtests=false \
            -Dx11_backend=false
          meson compile -C build
          sudo meson install -C build
          sudo cp -a $INSTDIR/include/gtk-3.0/gdk/quartz/gdkquartzwindow.h /opt/local/include/gtk-3.0/gdk/quartz
          sudo cp -a $INSTDIR/lib/libgdk-3.0.dylib /opt/local/lib/libgdk-3.0.dylib

      - name: Prepare tarball
        run: |
          ARTIFACT_NAME="ART-toolchain_macOS-${OS_VERSION}_${{ matrix.arch }}.tar.gz"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
              echo "RELEASE_TAG=${ART_VERSION}" >> $GITHUB_ENV
              echo "RELEASE_MAKE_LATEST=true" >> $GITHUB_ENV
          else
              echo "RELEASE_TAG=nightly" >> $GITHUB_ENV
              echo "RELEASE_MAKE_LATEST=false" >> $GITHUB_ENV
          fi
          sudo tar czf "$ARTIFACT_NAME" /opt/local /opt/art-deps

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_TAG }}
          allowUpdates: true
          makeLatest: ${{ env.RELEASE_MAKE_LATEST }}
          artifacts: ${{ env.ARTIFACT_NAME }}
